C Sharp/SecondWebMVC/SecondWebMVC/Models/Cliente.cs
namespace SecondWebMVC.Models;

public class Cliente : Persona
{
    public string Correo { get; set; } = string.Empty;
    public string Direccion { get; set; } = string.Empty;
    public string Telefono { get; set; }  = string.Empty;
}

C Sharp/SecondWebMVC/SecondWebMVC/Models/ErrorViewModel.cs
namespace SecondWebMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

C Sharp/SecondWebMVC/SecondWebMVC/Models/Persona.cs
namespace SecondWebMVC.Models;

public abstract class Persona
{
    public int Id { get; set; }
    public string Nombre { get; set; } = string.Empty;
    public string Apellido { get; set; } = string.Empty;
    public string Sexo { get; set; } = string.Empty; // h.Hombre ° m.Mujer
}

C Sharp/SecondWebMVC/SecondWebMVC/Models/Producto.cs
namespace SecondWebMVC.Models;

public class Producto
{
    public int Id { get; set; }
    public string Nombre{ get; set; } = String.Empty;
    public double Precio{ get; set; }
    
    // Relación con Cliente
    public int ClienteId { get; set; }
    public Cliente? Cliente { get; set; }
}

C Sharp/SecondWebMVC/SecondWebMVC/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using SecondWebMVC.Models;

namespace SecondWebMVC.Controllers;

// Controlador encargado de manejar todas las acciones relacionadas con los Clientes
public class ClienteController : Controller
{
    // Lista estática que almacenará en memoria a todos los clientes creados en la aplicación
    // (NOTA: Al ser estática, los datos se comparten en todas las instancias del controlador mientras dure la ejecución)
    public static readonly List<Cliente> Clientes = [];

    // Acción que retorna la vista principal (Index) mostrando la lista completa de clientes
    public ActionResult Index()
    {
        return View(Clientes);
    }

    // Acción que muestra los detalles de un cliente específico según su Id
    public ActionResult Detalles(int id)
    {
        // Busca el cliente cuyo Id coincida con el parámetro recibido
        var cliente = Clientes.FirstOrDefault(c => c.Id == id);

        // Si no encuentra un cliente con ese Id, retorna un error 404 (NotFound)
        if (cliente == null) return NotFound();

        // Si lo encuentra, envía ese cliente a la vista para mostrar sus detalles
        return View(cliente);
    }

    // Acción que guarda un nuevo cliente en la lista
    public ActionResult Guardar(Cliente cliente)
    {
        /*
         * Lógica para asignar el Id del nuevo cliente:
         * - Si la lista ya tiene clientes: se obtiene el Id más alto con Clientes.Max(c => c.Id) y se le suma 1.
         * - Si la lista está vacía: se asigna el Id = 1.
         */
        cliente.Id = Clientes.Any() ? Clientes.Max(c => c.Id) + 1 : 1;

        // Agrega el cliente recibido a la lista
        Clientes.Add(cliente);

        // Redirige al usuario nuevamente a la lista de clientes (Index)
        return RedirectToAction("Index");
    }

    // Acción que permite editar los datos de un cliente existente
    public ActionResult Editar(Cliente clienteEditado)
    {
        // Busca en la lista el cliente que coincida con el ID del cliente editado
        var cliente = Clientes.FirstOrDefault(c => c.Id == clienteEditado.Id);

        // Si no existe un cliente con ese ID, devuelve un error 404
        if (cliente == null) return NotFound();

        // Si lo encuentra, actualiza cada campo con la nueva información recibida
        cliente.Nombre = clienteEditado.Nombre;
        cliente.Apellido = clienteEditado.Apellido;
        cliente.Sexo = clienteEditado.Sexo;
        cliente.Correo = clienteEditado.Correo;
        cliente.Direccion = clienteEditado.Direccion;
        cliente.Telefono = clienteEditado.Telefono;

        // Después de actualizar, redirige nuevamente a la lista de clientes
        return RedirectToAction("Index");
    }

    // Acción que elimina un cliente de la lista según su Id
    public ActionResult Eliminar(int id)
    {
        // Busca el cliente por Id y lo elimina directamente de la lista
        Clientes.Remove(Clientes.FirstOrDefault(c => c.Id == id)!);

        // Redirige a la lista actualizada de clientes
        return RedirectToAction("Index");
    }
}

C Sharp/SecondWebMVC/SecondWebMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SecondWebMVC.Models;

namespace SecondWebMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

C Sharp/SecondWebMVC/SecondWebMVC/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using SecondWebMVC.Models;

namespace SecondWebMVC.Controllers;

public class ProductoController : Controller
{
    private static readonly List<Producto> Productos = []; //Lista que guarda los Productos
    private static readonly List<Cliente> Clientes = ClienteController.Clientes; // reutilizar clientes

    public ActionResult Index() //Muestra los Productos
    {
        return View(Productos);
    }
    
    public ActionResult CrearProducto(Producto producto) //Crear un nuevo Producto
    {
        producto.Id = Productos.Any() ? Productos.Max(p => p.Id) +1 : 1;
        
        // Asociar al cliente
        var cliente = Clientes.FirstOrDefault(c => c.Id == producto.ClienteId);
        if (cliente == null) return NotFound();
        
        producto.Cliente = cliente;
        
        Productos.Add(producto);
        return RedirectToAction("Index");
    }

    public ActionResult EditarProducto(Producto productoEditado) //Editar un Producto.ID
    {
        var producto = Productos.FirstOrDefault(p => p.Id == productoEditado.Id);
        if (producto == null) return NotFound();
        
        producto.Id = productoEditado.Id;
        producto.Nombre = productoEditado.Nombre;
        producto.Precio = productoEditado.Precio;
        return RedirectToAction("Index");
    }

    public ActionResult EliminarProducto(int id) //Eliminar un Producto.ID
    {
        Productos.Remove(Productos.FirstOrDefault(p => p.Id == id)!);
        return RedirectToAction("Index");
    }
}

C Sharp/SecondWebMVC/SecondWebMVC/Views/Cliente/Detalles.cshtml
@model SecondWebMVC.Models.Cliente
<!-- El modelo que recibe esta vista es un solo objeto Cliente -->

<h1 class="text-center">Detalles del cliente</h1>

<div class="row">
    <!-- Columna izquierda: formulario para editar al cliente -->
    <div class="col-md-4"> <!-- Formulario Principal que Edita los Clientes -->
        <div class="card">
            <div class="card-body">
                <!-- El formulario envía la información al método Editar del ClienteController -->
                <form asp-action="Editar"> <!-- Campos: Nombre, Apellido, Correo, Dirección, Teléfono -->
                    <h6 class="text-center">Editar Cliente</h6>

                    <!-- Campo oculto que guarda el Id del cliente (no se modifica) -->
                    <input type="hidden" asp-for="Id"/>

                    <div class="row">
                        <!-- Campo editable para el Nombre -->
                        <div class="col p-1">
                            <input type="text" class="form-control" name="Nombre"
                                   placeholder="@Model.Nombre" value="@Model.Nombre">
                        </div>

                        <!-- Campo editable para el Apellido -->
                        <div class="col p-1">
                            <input type="text" class="form-control" name="Apellido"
                                   placeholder="@Model.Apellido" value="@Model.Apellido">
                        </div>
                        
                        <!-- Campo editable para el Sexo -->
                        <div class="p-1">
                            <input type="text" class="form-control" name="Sexo"
                                   placeholder="@Model.Sexo" value="@Model.Sexo">
                        </div>

                        <!-- Campo editable para el Correo -->
                        <div class="p-1">
                            <input type="email" class="form-control" name="Correo"
                                   placeholder="@Model.Correo" value="@Model.Correo">
                        </div>

                        <!-- Campo editable para la Dirección -->
                        <div class="p-1">
                            <input type="text" class="form-control" name="Direccion"
                                   placeholder="@Model.Direccion" value="@Model.Direccion">
                        </div>

                        <!-- Campo editable para el Teléfono -->
                        <div class="p-1">
                            <input type="text" class="form-control" name="Telefono"
                                   placeholder="@Model.Telefono" value="@Model.Telefono">
                        </div>
                    </div>

                    <hr>
                    <!-- Botón para guardar los cambios realizados en el cliente -->
                    <button type="submit" class="btn btn-success w-100">Guardar cambios</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Columna derecha: tabla que muestra la información actual del cliente -->
    <div class="col-md-8"> <!-- Tabla Principal que muestra los Detalles del Cliente-->
        <!-- Botón para regresar a la lista de clientes (Index) -->
        <a class="btn btn-primary" asp-action="Index" asp-controller="Cliente">Volver</a>

        <table class="table">
            <thead>
            <tr>
                <th scope="col">Id</th>        <!-- Encabezado Id -->
                <th scope="col">Nombre</th>    <!-- Encabezado Nombre -->
                <th scope="col">Apellido</th>  <!-- Encabezado Apellido -->
                <th scope="col">Sexo</th>      <!-- Encabezado Sexo -->
                <th scope="col">Correo</th>    <!-- Encabezado Correo -->
                <th scope="col">Dirección</th> <!-- Encabezado Dirección -->
                <th scope="col">Teléfono</th>  <!-- Encabezado Teléfono -->
            </tr>
            </thead>
            <tbody>
            <tr>
                <!-- Fila que muestra todos los datos actuales del cliente -->
                <td>@Model.Id</td>
                <td>@Model.Nombre</td>
                <td>@Model.Apellido</td>
                <td>@(Model.Sexo == "h" ? "❤" : "❤❤")</td>
                <td>@Model.Correo</td>
                <td>@Model.Direccion</td>
                <td>@Model.Telefono</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

C Sharp/SecondWebMVC/SecondWebMVC/Views/Cliente/Index.cshtml
@model IEnumerable<SecondWebMVC.Models.Cliente> 
<!-- El modelo que recibe esta vista es una lista (IEnumerable) de objetos Cliente -->

<h1 class="text-center">Administrador de Clientes</h1>
<a class="btn btn-primary m-2" asp-action="Index" asp-controller="Producto">Ir a Productos</a> <!-- Ir a Productos -->

<div class="row">
    <!-- Columna del formulario para registrar un nuevo cliente -->
    <div class="col-md-3"> <!-- Formulario Principal que Guarda los Clientes -->
        <div class="card">
            <div class="card-body">
                <!-- El formulario envía la información al método Guardar del ClienteController -->
                <form asp-action="Guardar">
                    <div class="row"> <!-- Campos de entrada: Nombre, Apellido, Correo, Dirección, Teléfono -->
                        <div class="col">
                            <label>Nombre</label>
                            <input type="text" class="form-control" name="Nombre">
                        </div>
                        <div class="col">
                            <label>Apellido</label>
                            <input type="text" class="form-control" name="Apellido">
                        </div>
                        <div>
                            <label>Sexo</label>
                            <input type="text" class="form-control" name="Sexo" placeholder="h.Hombre/ m.Mujer">
                        </div>
                        <div>
                            <label>Correo</label>
                            <input type="email" class="form-control" name="Correo">
                        </div>
                        <div>
                            <label>Dirección</label>
                            <input type="text" class="form-control" name="Direccion">
                        </div>
                        <div>
                            <label>Teléfono</label>
                            <input type="text" class="form-control" name="Telefono">
                        </div>
                    </div>
                    <hr>
                    <!-- Botón para enviar los datos y registrar el cliente -->
                    <button type="submit" class="btn btn-success w-100">Guardar Cliente</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Columna de la tabla que lista todos los clientes -->
    <div class="col-md-9"> <!-- Tabla Principal que muestra los Clientes-->
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Id</th>       <!-- Columna del Id del Cliente -->
                <th scope="col">Nombre</th>   <!-- Columna del Nombre -->
                <th scope="col">Apellido</th> <!-- Columna del Apellido -->
                <th scope="col">Detalles</th> <!-- Botón para ver Detalles -->
                <th scope="col">Eliminar</th> <!-- Botón para Eliminar -->
            </tr>
            </thead>
            <tbody>
            @if (Model.Any()) // Validar que la lista (Model) no esté vacía o nula
            {
                foreach (var cliente in Model) // Recorrer la lista de clientes
                {
                    <tr>
                        <td>@cliente.Id</td>         <!-- Muestra el Id -->
                        <td>@cliente.Nombre</td>     <!-- Muestra el Nombre -->
                        <td>@cliente.Apellido</td>   <!-- Muestra el Apellido -->
                        <td>
                            <!-- Botón que redirige a la acción Detalles enviando el Id -->
                            <a class="btn btn-primary" asp-action="Detalles" asp-controller="Cliente"
                               asp-route-id="@cliente.Id">Detalles</a>
                        </td>
                        <td>
                            <!-- Botón que redirige a la acción Eliminar enviando el Id -->
                            <a class="btn btn-danger" asp-action="Eliminar" asp-controller="Cliente"
                               asp-route-id="@cliente.Id">Eliminar</a>
                        </td>
                    </tr>
                }
            }
            else
            {
                <!-- Si no hay clientes en la lista, mostrar este mensaje -->
                <p class="text-center text-danger">¡No hay Clientes!</p>
            }
            </tbody>
        </table>
    </div>
</div>

C Sharp/SecondWebMVC/SecondWebMVC/Views/Producto/Index.cshtml
@model IEnumerable<SecondWebMVC.Models.Producto>
@using SecondWebMVC.Controllers

@{
    // obtener clientes
    var clientes = ClienteController.Clientes; // Clientes es público
}
<h1 class="text-center">Administrador de Productos</h1>
<a class="btn btn-primary m-2" asp-action="Index" asp-controller="Cliente">Ir A Clientes</a> <!-- Ir a Clientes -->

<div class="row">
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <!-- Formulario para agregar un nuevo Producto -->
                <form asp-action="CrearProducto">
                    <div class="row">
                        <div>
                            <label>Nombre Producto</label>
                            <input type="text" class="form-control" name="Nombre">
                        </div>
                        <div>
                            <label>Precio Producto</label>
                            <input type="number" class="form-control" name="Precio">
                        </div>
                        <div>
                            <label>Cliente</label>
                            <select name="ClienteId" class="form-control">
                                <option value="">-- Seleccione un cliente --</option>
                                @foreach (var c in clientes)
                                {
                                    <option value="@c.Id">@c.Nombre @c.Apellido</option>
                                }
                            </select>
                        </div>
                    </div>
                    <hr>
                    <!-- Botón para enviar los datos y registrar el cliente -->
                    <button type="submit" class="btn btn-success w-100">Guardar Producto</button>
                </form>
            </div>
        </div>
    </div>
    
    <!-- Columna de la tabla que lista todos los clientes -->
    <div class="col-md-9"> <!-- Tabla Principal que muestra los Clientes-->
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Id</th>       <!-- Columna del Id del Cliente -->
                <th scope="col">Nombre</th>   <!-- Columna del Nombre -->
                <th scope="col">Precio</th>   <!-- Columna del Precio -->
                <th scope="col">Cliente</th>  <!-- Columna del Cliente -->
                <th scope="col">Eliminar</th> <!-- Botón para Eliminar -->
            </tr>
            </thead>
            <tbody>
            @if (Model.Any()) // Validar que la lista (Model) no esté vacía o nula
            {
                foreach (var producto in Model) // Recorrer la lista de Productos
                {
                    <tr>
                        <td>@producto.Id</td>         <!-- Muestra el Id -->
                        <td>@producto.Nombre</td>     <!-- Muestra el Nombre -->
                        <td>@producto.Precio</td>     <!-- Muestra el Precio -->
                        <td>[@producto.ClienteId] @producto.Cliente?.Nombre</td> <!-- Muestra el Id.NombreCliente -->
                        <td>
                            <!-- Botón que redirige a la acción Eliminar enviando el Id -->
                            <a class="btn btn-danger" asp-action="EliminarProducto" asp-controller="Producto"
                               asp-route-id="@producto.Id">Eliminar</a>
                        </td>
                    </tr>
                }
            }
            else
            {
                <!-- Si no hay Productos en la lista, mostrar este mensaje -->
                <p class="text-center text-danger">¡No hay Productos!</p>
            }
            </tbody>
        </table>
    </div>
</div>

C Sharp/SecondWebMVC/SecondWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SecondWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SecondWebMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SecondWebMVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - SecondWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>